[build.default]
foundry-project-root       = '.'
regen                      = true
rekompile                  = true
verbose                    = false
debug                      = false
auxiliary-lemmas           = true

[prove.default]
foundry-project-root       = '.'
schedule                   = 'CANCUN'
verbose                    = false
debug                      = false
max-depth                  = 100000
max-iterations             = 10000
reinit                     = false
cse                        = false
workers                    = 1
max-frontier-parallel      = 6
maintenance-rate           = 128
assume-defined             = false
no-log-succ-rewrites       = true
no-stack-checks            = true
optimize-kcfg              = true
kore-rpc-command           = 'kore-rpc-booster --no-post-exec-simplify --equation-max-recursion 20 --equation-max-iterations 1000 --fallback-on Aborted'
failure-information        = true
counterexample-information = true
minimize-proofs            = false
fail-fast                  = true
smt-timeout                = 60000
smt-retry-limit            = 0
break-every-step           = false
break-on-jumpi             = false
break-on-calls             = false
break-on-storage           = false
break-on-basic-blocks      = false
break-on-cheatcodes        = false
auto_abstract              = true
run-constructor            = false
match-test                 = [
        "LiFiDiamondTest.test",
        "DexManagerFacetTest.test",
        "SwapperV2Test.test",
        "TransferrableOwnershipTest.test",
        "LibUtilTest.test",
        "ERC20ProxyTest.test",
        "LiFiTimelockControllerTest.test",
        "TestBaseFacet.test",
        #"AccessManagerFacetTest.test",
        #"AcrossFacetTest.testRevert_FailsIfCalledWithOutdatedQuote",
        #"AcrossFacetPackedTest.test",
        #"AcrossFacetPackedV3Test.test",
        #"AcrossFacetV3Test.test",
        #"AllBridgeFacetTest.test",
        #"ExecutorTest.test", reason: vm.makePersistent
        #"FeeCollectorTest.test", reason: vm.deal
        #"TokenWrapperTest.test", reason: vm.deal
    ]

[show.default]
foundry-project-root       = '.'
verbose                    = false
debug                      = false
